name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  
  #HELPERS
  bloc: ^8.1.2
  auto_route: ^7.3.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  connectivity_plus: ^4.0.2
  freezed_annotation: ^2.4.1

    #custom package
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  ping_discover_network:
    git:
      url: https://github.com/kahero-team/ping_discover_network.git
  esc_pos_bluetooth:
    git:
      url: https://github.com/kahero-team/esc_pos_bluetooth.git
  esc_pos_printer:
    git:
      url: https://github.com/kahero-team/esc_pos_printer.git
  esc_pos_utils:
    git:
      url: https://github.com/kahero-team/esc_pos_utils_ticket.git
  country_code_picker:
    git:
      url: https://github.com/kahero-team/CountryCodePicker.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.1

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
